const fs = require("fs");

// 1. Add generateProgramAction to program-actions.ts
const paPath = "actions/program-actions.ts";
let paContent = fs.readFileSync(paPath, "utf-8");

if (!paContent.includes("generateProgramAction")) {
  paContent = `import { generateProgram } from "@/lib/services/ai.service";\n` + paContent;
  
  const actionCode = `
export async function generateProgramAction(params: any) {
  const user = await getClinicianUser();
  if (!user) return { success: false as const, error: "Unauthorized" };

  try {
    const aiPlan = await generateProgram(params);

    const program = await prisma.program.create({
      data: {
        name: aiPlan.name,
        description: aiPlan.description || "Generated by AI",
        isTemplate: true,
        clinicianId: user.id,
        aiGenerationParams: params,
        workouts: {
          create: aiPlan.workouts.map((w: any) => ({
            name: w.name,
            dayIndex: w.dayIndex,
            orderIndex: w.dayIndex,
            blocks: {
              create: w.blocks.map((b: any) => ({
                type: b.type || "NORMAL",
                orderIndex: b.orderIndex,
                exercises: {
                  create: b.exercises.map((e: any, idx: number) => ({
                    exerciseId: e.exerciseId,
                    orderIndex: e.orderIndex,
                    sets: {
                      create: Array.from({ length: e.sets || 1 }).map((_, i) => ({
                        orderIndex: i,
                        targetReps: e.reps?.toString() || "10"
                      }))
                    }
                  }))
                }
              }))
            }
          }))
        }
      }
    });

    revalidatePath("/programs");
    return { success: true as const, data: program.id };
  } catch (error) {
    console.error("Failed to generate program:", error);
    return { success: false as const, error: "Failed to generate program" };
  }
}
`;
  paContent += "\n" + actionCode;
  fs.writeFileSync(paPath, paContent);
  console.log("Added generateProgramAction!");
} else {
  console.log("Already has action");
}

// 2. Add generateProgram to ai.service.ts
const aiPath = "lib/services/ai.service.ts";
let aiContent = fs.readFileSync(aiPath, "utf-8");

if (!aiContent.includes("export async function generateProgram(")) {
  const serviceCode = `
export interface GeneratedProgramWorkoutBlock {
  type: string;
  orderIndex: number;
  exercises: {
    exerciseId: string;
    orderIndex: number;
    sets: number;
    reps: string;
  }[];
}

export interface GeneratedProgramWorkout {
  name: string;
  dayIndex: number;
  blocks: GeneratedProgramWorkoutBlock[];
}

export interface GeneratedProgram {
  name: string;
  description?: string;
  workouts: GeneratedProgramWorkout[];
}

export async function generateProgram(
  params: GenerateWorkoutParams
): Promise<GeneratedProgram> {
  const generatedPlan = await generateWorkoutPlan(params);

  const workoutsMap = new Map<number, GeneratedProgramWorkout>();

  generatedPlan.exercises.forEach((ex) => {
    const day = ex.dayOfWeek || 1;
    if (!workoutsMap.has(day)) {
      workoutsMap.set(day, {
        name: \`Day \${day} Workout\`,
        dayIndex: day,
        blocks: [],
      });
    }
    const workout = workoutsMap.get(day)!;

    let block = workout.blocks.find((b) => b.type === ex.phase.toUpperCase() || b.type === "NORMAL");
    if (!block) {
      block = {
        type: ["WARMUP", "ACTIVATION", "STRENGTHENING", "MOBILITY", "COOLDOWN"].includes(ex.phase.toUpperCase()) ? ex.phase.toUpperCase() : "NORMAL",
        orderIndex: workout.blocks.length,
        exercises: [],
      };
      workout.blocks.push(block);
    }
    
    block.exercises.push({
      exerciseId: ex.exerciseId,
      orderIndex: block.exercises.length,
      sets: ex.sets || 3,
      reps: ex.reps?.toString() || "10",
    });
  });

  const workouts = Array.from(workoutsMap.values()).sort((a, b) => a.dayIndex - b.dayIndex);

  return {
    name: generatedPlan.title || "AI Generated Program",
    description: generatedPlan.description,
    workouts,
  };
}
`;
  aiContent += "\n" + serviceCode;
  fs.writeFileSync(aiPath, aiContent);
  console.log("Added generateProgram!");
} else {
  console.log("Already has generateProgram");
}
