import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type ExerciseSeed = {
  name: string;
  description: string;
  bodyRegion: "LOWER_BODY" | "UPPER_BODY" | "CORE" | "FULL_BODY" | "BALANCE" | "FLEXIBILITY";
  difficultyLevel: "BEGINNER" | "INTERMEDIATE" | "ADVANCED";
  exercisePhase: "WARMUP" | "ACTIVATION" | "STRENGTHENING" | "MOBILITY" | "COOLDOWN";
  musclesTargeted: string[];
  equipmentRequired: string[];
  contraindications: string[];
  instructions: string;
  commonMistakes: string;
  defaultSets: number;
  defaultReps: number | null;
  defaultHoldSeconds: number | null;
  cuesThumbnail: string;
  videoUrl: string | null;
};

type TemplateSet = {
  reps?: number | null;
  durationSeconds?: number | null;
};

type TemplateExercise = {
  name: string;
  sets: TemplateSet[];
  notes?: string | null;
  restSeconds?: number | null;
};

type TemplateBlock = {
  name: string;
  type: "NORMAL" | "WARMUP" | "COOLDOWN" | "SUPERSET" | "CIRCUIT" | "AMRAP" | "EMOM";
  rounds?: number;
  notes?: string | null;
  exercises: TemplateExercise[];
};

type TemplateWorkout = {
  name: string;
  description: string;
  dayIndex: number;
  orderIndex: number;
  estimatedMinutes: number;
  blocks: TemplateBlock[];
};

function makeSets(count: number, template: TemplateSet): TemplateSet[] {
  return Array.from({ length: count }, () => ({ ...template }));
}

function seedExercise(seed: ExerciseSeed): ExerciseSeed {
  return seed;
}

const exerciseSeeds: ExerciseSeed[] = [
  seedExercise({
    name: "Heel Elevated Squat",
    description: "Heel-elevated squat that biases the quads and keeps the torso upright.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["quadriceps", "gluteus maximus"],
    equipmentRequired: ["plate or wedge"],
    contraindications: ["acute knee pain"],
    instructions: "Stand with the heels elevated and squat down with an upright torso. Drive back up through the midfoot.",
    commonMistakes: "Letting the heels drop, collapsing the knees inward, or losing trunk position.",
    defaultSets: 4,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Heels up, torso tall, knees track over toes.",
    videoUrl: "https://www.youtube.com/watch?v=UvxTioyshwQ",
  }),
  seedExercise({
    name: "Depth Jump",
    description: "Reactive drop-and-rebound jump for lower-body power.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["quadriceps", "glutes", "calves"],
    equipmentRequired: ["box"],
    contraindications: ["acute knee pain", "achilles pain"],
    instructions: "Step off a low box, land softly, then rebound quickly into a vertical jump.",
    commonMistakes: "Using too high a box, sticking too long on the floor, or landing stiff.",
    defaultSets: 4,
    defaultReps: 4,
    defaultHoldSeconds: null,
    cuesThumbnail: "Soft landing. Fast rebound.",
    videoUrl: "https://www.youtube.com/watch?v=bMHL5xqKn3E",
  }),
  seedExercise({
    name: "Full Range Split Squat",
    description: "Unilateral split squat through full hip and knee range.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["quadriceps", "gluteus maximus", "adductors"],
    equipmentRequired: [],
    contraindications: ["acute hip flexor pain"],
    instructions: "Lower into a deep split squat and return to standing with control.",
    commonMistakes: "Cutting depth short or letting the front knee cave inward.",
    defaultSets: 4,
    defaultReps: 8,
    defaultHoldSeconds: null,
    cuesThumbnail: "Stay tall. Full depth. Push through front foot.",
    videoUrl: "https://www.youtube.com/watch?v=kBioqEJvIqQ",
  }),
  seedExercise({
    name: "Skiers",
    description: "Lateral power and deceleration drill.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["gluteus medius", "quadriceps", "calves"],
    equipmentRequired: [],
    contraindications: ["acute ankle sprain", "groin pain"],
    instructions: "Bound side to side in a skating pattern, landing softly and driving back out.",
    commonMistakes: "Landing stiff or allowing the knees to collapse inward.",
    defaultSets: 4,
    defaultReps: 8,
    defaultHoldSeconds: null,
    cuesThumbnail: "Push side to side. Stick the landing.",
    videoUrl: "https://www.youtube.com/watch?v=usZgF8TBWcA",
  }),
  seedExercise({
    name: "Hanging Knee Raise",
    description: "Core drill for hip flexion and trunk control.",
    bodyRegion: "CORE",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["rectus abdominis", "hip flexors"],
    equipmentRequired: ["pull-up bar"],
    contraindications: ["shoulder pain with hanging"],
    instructions: "Hang from a bar and raise the knees toward the chest without swinging.",
    commonMistakes: "Using momentum, shrugging up, or arching the low back.",
    defaultSets: 4,
    defaultReps: 15,
    defaultHoldSeconds: null,
    cuesThumbnail: "No swing. Ribs down.",
    videoUrl: "https://www.youtube.com/watch?v=l7OroezzX9k",
  }),
  seedExercise({
    name: "Copenhagen Plank",
    description: "Adductor and side-core hold.",
    bodyRegion: "CORE",
    difficultyLevel: "ADVANCED",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["adductors", "obliques", "gluteus medius"],
    equipmentRequired: ["bench"],
    contraindications: ["acute groin strain"],
    instructions: "Hold a side plank with the top leg supported on a bench or box.",
    commonMistakes: "Dropping the hips or rotating the trunk.",
    defaultSets: 4,
    defaultReps: null,
    defaultHoldSeconds: 30,
    cuesThumbnail: "Hips high. Body long.",
    videoUrl: "https://www.youtube.com/watch?v=48wlc5zn02A",
  }),
  seedExercise({
    name: "Couch Stretch",
    description: "Hip flexor and quad stretch used in cooldowns.",
    bodyRegion: "FLEXIBILITY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "COOLDOWN",
    musclesTargeted: ["hip flexors", "quadriceps"],
    equipmentRequired: ["wall"],
    contraindications: ["anterior knee pain"],
    instructions: "Set the back leg against the wall and sit tall into a gentle hip flexor stretch.",
    commonMistakes: "Arching the back or twisting the pelvis.",
    defaultSets: 2,
    defaultReps: null,
    defaultHoldSeconds: 30,
    cuesThumbnail: "Tall torso, squeeze back glute.",
    videoUrl: "https://www.youtube.com/watch?v=nTJaGnjUkTY",
  }),
  seedExercise({
    name: "Hamstring Stretch (Supine)",
    description: "Supine hamstring stretch with band support.",
    bodyRegion: "FLEXIBILITY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "COOLDOWN",
    musclesTargeted: ["hamstrings"],
    equipmentRequired: ["band or strap"],
    contraindications: ["acute hamstring strain"],
    instructions: "Lie on your back and raise one leg with a band until a gentle stretch is felt.",
    commonMistakes: "Pulling too hard or bending the knee aggressively.",
    defaultSets: 2,
    defaultReps: null,
    defaultHoldSeconds: 30,
    cuesThumbnail: "Gentle pull. Relax the other leg.",
    videoUrl: "https://www.youtube.com/watch?v=Gt0vqmdKhqU",
  }),
  seedExercise({
    name: "Calf Stretch with Toes Up",
    description: "Dorsiflexion-biased calf stretch.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "COOLDOWN",
    musclesTargeted: ["gastrocnemius", "soleus"],
    equipmentRequired: ["wall"],
    contraindications: ["acute achilles pain"],
    instructions: "Stand with toes up and heel grounded, then lean forward until the calf stretches.",
    commonMistakes: "Letting the heel lift or bouncing in the stretch.",
    defaultSets: 2,
    defaultReps: null,
    defaultHoldSeconds: 30,
    cuesThumbnail: "Toes up, heel down.",
    videoUrl: "https://www.youtube.com/watch?v=-JATrL0meVM",
  }),
  seedExercise({
    name: "Single-Leg Pogo Hops",
    description: "Single-leg ankle stiffness drill.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["calves", "foot intrinsics"],
    equipmentRequired: [],
    contraindications: ["acute ankle sprain"],
    instructions: "Hop lightly on one leg with quick contacts and a stiff ankle.",
    commonMistakes: "Losing rhythm or turning it into a high jump.",
    defaultSets: 2,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Quick and light.",
    videoUrl: "https://www.youtube.com/watch?v=Yq75-6SUn7A",
  }),
  seedExercise({
    name: "Double-Leg Pogo Hops",
    description: "Two-leg ankle stiffness drill.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["calves", "foot intrinsics"],
    equipmentRequired: [],
    contraindications: ["acute ankle sprain"],
    instructions: "Hop on both feet with minimal knee bend and fast contacts.",
    commonMistakes: "Sinking too deep or landing heavily.",
    defaultSets: 2,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Fast contacts, tall posture.",
    videoUrl: "https://www.youtube.com/watch?v=YqLplUCanfw",
  }),
  seedExercise({
    name: "Double-Leg Small Pogo Hops",
    description: "Short-amplitude pogo prep drill.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "WARMUP",
    musclesTargeted: ["calves", "foot intrinsics"],
    equipmentRequired: [],
    contraindications: ["acute ankle sprain"],
    instructions: "Perform very small, fast pogo hops with light contacts.",
    commonMistakes: "Making the hops too big or noisy.",
    defaultSets: 2,
    defaultReps: 20,
    defaultHoldSeconds: null,
    cuesThumbnail: "Tiny bounce. Stay springy.",
    videoUrl: "https://www.youtube.com/watch?v=j0nl5dWuqN4",
  }),
  seedExercise({
    name: "Double-Leg Pogo for Height",
    description: "Pogo variation emphasizing a slightly higher rebound.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["calves", "quads"],
    equipmentRequired: [],
    contraindications: ["acute ankle pain"],
    instructions: "Bounce with a stiffer ankle and a slightly higher rebound.",
    commonMistakes: "Turning it into a squat jump.",
    defaultSets: 2,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Bounce up, stay stiff.",
    videoUrl: "https://www.youtube.com/watch?v=Oy4GBFpMYtM",
  }),
  seedExercise({
    name: "Split-Stance Slalom Hops",
    description: "Split-stance lateral hop drill for control and rhythm.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["gluteus medius", "adductors", "calves"],
    equipmentRequired: [],
    contraindications: ["acute ankle sprain", "groin pain"],
    instructions: "Hop side-to-side in a split stance with quiet landings and stable hips.",
    commonMistakes: "Twisting through the trunk or landing stiff.",
    defaultSets: 2,
    defaultReps: 20,
    defaultHoldSeconds: null,
    cuesThumbnail: "Stable hips, quick feet.",
    videoUrl: "https://www.youtube.com/watch?v=p_ULnqHyPXA",
  }),
  seedExercise({
    name: "Skips for Height",
    description: "High-knee skipping drill with vertical intent.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "WARMUP",
    musclesTargeted: ["hip flexors", "calves", "glutes"],
    equipmentRequired: [],
    contraindications: ["acute calf strain"],
    instructions: "Drive the knee up and pop off the ground with a tall torso.",
    commonMistakes: "Leaning back or losing rhythm.",
    defaultSets: 2,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Knee up, pop off the floor.",
    videoUrl: "https://www.youtube.com/watch?v=ml8GIEIdwmg",
  }),
  seedExercise({
    name: "Mario's for Height",
    description: "Power skip drill with strong knee drive.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "WARMUP",
    musclesTargeted: ["hip flexors", "calves", "hamstrings"],
    equipmentRequired: [],
    contraindications: ["acute calf strain"],
    instructions: "Skip with a strong knee lift and fast rhythm.",
    commonMistakes: "Slowing down or collapsing at the hips.",
    defaultSets: 2,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Drive the knee, stay springy.",
    videoUrl: "https://www.youtube.com/watch?v=Sa5Fs5gw6R8",
  }),
  seedExercise({
    name: "Broad Jump",
    description: "Horizontal power jump from a standing start.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["glutes", "hamstrings", "quads"],
    equipmentRequired: [],
    contraindications: ["acute knee pain"],
    instructions: "Jump forward explosively and stick the landing softly.",
    commonMistakes: "Landing stiff or failing to absorb quietly.",
    defaultSets: 2,
    defaultReps: 5,
    defaultHoldSeconds: null,
    cuesThumbnail: "Jump far, land soft.",
    videoUrl: "https://www.youtube.com/watch?v=7Du1KbwCdUk",
  }),
  seedExercise({
    name: "Consecutive Broad Jumps",
    description: "Repeated broad jumps for horizontal elasticity.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["glutes", "hamstrings", "calves"],
    equipmentRequired: [],
    contraindications: ["acute knee pain"],
    instructions: "Perform broad jumps back-to-back with quick reloading between each jump.",
    commonMistakes: "Pausing too long or losing body position.",
    defaultSets: 2,
    defaultReps: 3,
    defaultHoldSeconds: null,
    cuesThumbnail: "Land, reload, jump again.",
    videoUrl: "https://www.youtube.com/watch?v=tQ-vJh-G7EI",
  }),
  seedExercise({
    name: "Lateral Broad Jump",
    description: "Side-to-side horizontal jump.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["gluteus medius", "quads", "calves"],
    equipmentRequired: [],
    contraindications: ["acute ankle sprain"],
    instructions: "Jump laterally, land softly, and stabilize before the next rep.",
    commonMistakes: "Letting the knee cave inward or losing balance.",
    defaultSets: 2,
    defaultReps: 5,
    defaultHoldSeconds: null,
    cuesThumbnail: "Jump sideways. Stick the landing.",
    videoUrl: "https://www.youtube.com/watch?v=0JalArKU0tc",
  }),
  seedExercise({
    name: "Bounds",
    description: "Alternating power bounds used to build sprint mechanics and elastic strength.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["glutes", "hamstrings", "calves"],
    equipmentRequired: [],
    contraindications: ["acute hamstring strain"],
    instructions: "Skip aggressively with long stride length and powerful projection off each leg.",
    commonMistakes: "Overreaching, collapsing at the hips, or making the contacts too slow.",
    defaultSets: 2,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Long stride. Quick switch. Drive forward.",
    videoUrl: "https://www.youtube.com/watch?v=eIjuMzIFREs",
  }),
  seedExercise({
    name: "Standing Triple Jump",
    description: "Three-jump horizontal power series.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["glutes", "hamstrings", "quads"],
    equipmentRequired: [],
    contraindications: ["acute knee pain"],
    instructions: "Perform three explosive jumps in sequence, using each landing to load the next takeoff.",
    commonMistakes: "Rushing the sequence or losing balance.",
    defaultSets: 3,
    defaultReps: 3,
    defaultHoldSeconds: null,
    cuesThumbnail: "Three jumps. Smooth rhythm.",
    videoUrl: "https://www.youtube.com/watch?v=FvutodRvNLA",
  }),
  seedExercise({
    name: "Barbell RDL",
    description: "Romanian deadlift with a barbell.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["hamstrings", "gluteus maximus", "erector spinae"],
    equipmentRequired: ["barbell"],
    contraindications: ["acute low-back pain"],
    instructions: "Hinge at the hips and keep the bar close as you lower and raise it.",
    commonMistakes: "Squatting the movement or rounding the low back.",
    defaultSets: 4,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Hips back. Bar close.",
    videoUrl: "https://www.youtube.com/watch?v=uhghy9pFIPY",
  }),
  seedExercise({
    name: "Dumbbell Seated Good Morning",
    description: "Seated hinge drill for hamstrings and posterior chain.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["hamstrings", "glutes", "erector spinae"],
    equipmentRequired: ["dumbbell", "bench"],
    contraindications: ["acute low-back pain"],
    instructions: "Sit tall on a bench, hinge forward from the hips, then return with control.",
    commonMistakes: "Rounding the spine or turning it into a sit-up.",
    defaultSets: 4,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Hinge from the hips.",
    videoUrl: "https://www.youtube.com/watch?v=vQ1m4L5_0ZQ",
  }),
  seedExercise({
    name: "Contralateral Bulgarian Split Squat",
    description: "Rear-foot-elevated split squat loaded on the opposite side.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["quadriceps", "glutes", "adductors"],
    equipmentRequired: ["bench", "dumbbell"],
    contraindications: ["acute knee pain"],
    instructions: "Hold the dumbbell opposite the front leg and descend through a full split squat.",
    commonMistakes: "Leaning too far forward or allowing the knee to cave inward.",
    defaultSets: 4,
    defaultReps: 6,
    defaultHoldSeconds: null,
    cuesThumbnail: "Opposite-side load. Full control.",
    videoUrl: "https://www.youtube.com/watch?v=GWicPIBm9nQ",
  }),
  seedExercise({
    name: "Single-Leg Slider Hamstring Curl",
    description: "Hamstring curl performed with one heel on a slider or towel.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["hamstrings", "gluteus maximus"],
    equipmentRequired: ["slider or towel"],
    contraindications: ["acute hamstring strain"],
    instructions: "Bridge up, extend the leg slowly, then curl it back without dropping the hips.",
    commonMistakes: "Letting the hips sag or rushing the curl.",
    defaultSets: 4,
    defaultReps: 6,
    defaultHoldSeconds: null,
    cuesThumbnail: "Hips high. Slow out, strong back.",
    videoUrl: "https://www.youtube.com/watch?v=OI6DZ4CERyU",
  }),
  seedExercise({
    name: "Kneeling Overhead Rotational Slam",
    description: "Med ball rotational slam from kneeling.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["obliques", "shoulders", "lats"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["painful overhead motion"],
    instructions: "From kneeling, rotate and slam the ball down with force.",
    commonMistakes: "Using the low back or moving too slowly.",
    defaultSets: 3,
    defaultReps: 6,
    defaultHoldSeconds: null,
    cuesThumbnail: "Rotate, reach, slam.",
    videoUrl: "https://www.youtube.com/watch?v=7Ep2LCv25dE",
  }),
  seedExercise({
    name: "Half-Kneeling Overhead Rotational Slam",
    description: "Half-kneeling rotational slam for trunk control and power.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["obliques", "shoulders", "glutes"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["painful kneeling position"],
    instructions: "From half-kneeling, rotate through the torso and slam the ball overhead/downward.",
    commonMistakes: "Spinning through the low back or losing balance.",
    defaultSets: 3,
    defaultReps: 6,
    defaultHoldSeconds: null,
    cuesThumbnail: "Half-kneel. Rotate hard.",
    videoUrl: "https://www.youtube.com/watch?v=C_v4SKtL7Zk",
  }),
  seedExercise({
    name: "Split-Stance Overhead Rotational Slam",
    description: "Split-stance rotational slam for power and coordination.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["obliques", "glutes", "shoulders"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["painful trunk rotation"],
    instructions: "Use a split stance and rotate aggressively through the torso to slam the ball.",
    commonMistakes: "Letting the pelvis spin out or losing balance.",
    defaultSets: 3,
    defaultReps: 6,
    defaultHoldSeconds: null,
    cuesThumbnail: "Split stance. Slam with intent.",
    videoUrl: "https://www.youtube.com/watch?v=sEFy-zchoKA",
  }),
  seedExercise({
    name: "Kneeling Scoop Toss",
    description: "Kneeling med ball scoop toss.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["shoulders", "trunk", "triceps"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["painful kneeling position"],
    instructions: "From kneeling, scoop the ball and toss it forward with an explosive finish.",
    commonMistakes: "Over-arching the back or throwing too slowly.",
    defaultSets: 3,
    defaultReps: 6,
    defaultHoldSeconds: null,
    cuesThumbnail: "Kneel tall. Scoop and launch.",
    videoUrl: "https://www.youtube.com/watch?v=c6TvkYWqJq8",
  }),
  seedExercise({
    name: "Half-Kneeling Scoop Toss",
    description: "Half-kneeling scoop toss for anti-rotation control.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["obliques", "glutes", "shoulders"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["painful kneeling position"],
    instructions: "Load the hip and toss the ball from the half-kneeling position.",
    commonMistakes: "Spinning through the low back.",
    defaultSets: 3,
    defaultReps: 6,
    defaultHoldSeconds: null,
    cuesThumbnail: "Load, rotate, toss.",
    videoUrl: "https://www.youtube.com/watch?v=T1AxG_TN9hA",
  }),
  seedExercise({
    name: "Split-Stance Scoop Toss",
    description: "Split-stance scoop toss for total-body power.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["glutes", "core", "shoulders"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["acute ankle pain"],
    instructions: "Set in a split stance and scoop toss the ball forward with force.",
    commonMistakes: "Losing the split-stance base or moving too slowly.",
    defaultSets: 3,
    defaultReps: 6,
    defaultHoldSeconds: null,
    cuesThumbnail: "Split stance, hard toss.",
    videoUrl: "https://www.youtube.com/watch?v=gZ8I11oC7tQ",
  }),
  seedExercise({
    name: "Step Back Scoop Toss",
    description: "Backward step-and-load scoop toss.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["glutes", "hamstrings", "core"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["acute knee pain"],
    instructions: "Take a small step back to load the hips, then scoop toss forward.",
    commonMistakes: "Taking too large of a step or spinning the trunk.",
    defaultSets: 5,
    defaultReps: 3,
    defaultHoldSeconds: null,
    cuesThumbnail: "Step back, load, toss.",
    videoUrl: "https://www.youtube.com/watch?v=535h9EjA-lY",
  }),
  seedExercise({
    name: "Shuffle Scoop Toss",
    description: "Lateral shuffle into a scoop toss.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["glutes", "core", "shoulders"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["acute ankle pain"],
    instructions: "Shuffle into position and immediately scoop toss the ball.",
    commonMistakes: "Getting upright too early or losing rhythm.",
    defaultSets: 4,
    defaultReps: 6,
    defaultHoldSeconds: null,
    cuesThumbnail: "Shuffle, load, toss.",
    videoUrl: "https://www.youtube.com/watch?v=swsLUlX5KbY",
  }),
  seedExercise({
    name: "Chin-Up Iso",
    description: "Isometric chin-up hold.",
    bodyRegion: "UPPER_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["lats", "biceps", "mid back"],
    equipmentRequired: ["pull-up bar"],
    contraindications: ["painful hanging or gripping"],
    instructions: "Pull to the top chin-up position and hold with the chest tall.",
    commonMistakes: "Shrugging up or losing the hold too quickly.",
    defaultSets: 5,
    defaultReps: null,
    defaultHoldSeconds: 30,
    cuesThumbnail: "Hold high. Chest tall.",
    videoUrl: "https://www.youtube.com/watch?v=Z8nhpFfKLAE",
  }),
  seedExercise({
    name: "Half-Kneeling Woodchopper",
    description: "Half-kneeling rotational core drill.",
    bodyRegion: "CORE",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["obliques", "glutes", "serratus anterior"],
    equipmentRequired: ["cable or band"],
    contraindications: ["acute low-back pain"],
    instructions: "From half-kneeling, pull the cable or band diagonally across the body with control.",
    commonMistakes: "Rotating through the low back.",
    defaultSets: 2,
    defaultReps: 6,
    defaultHoldSeconds: null,
    cuesThumbnail: "Rotate with control.",
    videoUrl: "https://www.youtube.com/watch?v=KOh8cxe2ziE",
  }),
  seedExercise({
    name: "Dead Hang",
    description: "Passive hanging hold for grip and shoulder decompression.",
    bodyRegion: "UPPER_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "COOLDOWN",
    musclesTargeted: ["grip", "latissimus dorsi"],
    equipmentRequired: ["pull-up bar"],
    contraindications: ["painful shoulder impingement"],
    instructions: "Hang from a bar with relaxed shoulders and steady breathing.",
    commonMistakes: "Shrugging up or turning the hang into a swing.",
    defaultSets: 3,
    defaultReps: null,
    defaultHoldSeconds: 30,
    cuesThumbnail: "Long arms. Relax shoulders.",
    videoUrl: "https://www.youtube.com/watch?v=PlAE67ovNEo",
  }),
  seedExercise({
    name: "Side Plank",
    description: "Lateral core endurance hold.",
    bodyRegion: "CORE",
    difficultyLevel: "BEGINNER",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["obliques", "gluteus medius"],
    equipmentRequired: [],
    contraindications: ["shoulder pain in side plank"],
    instructions: "Stack the body in a side plank and keep the hips lifted.",
    commonMistakes: "Letting the hips drop or rotating forward.",
    defaultSets: 2,
    defaultReps: null,
    defaultHoldSeconds: 30,
    cuesThumbnail: "Long line head to heel.",
    videoUrl: "https://www.youtube.com/watch?v=iNbH7_edNI8",
  }),
  seedExercise({
    name: "Single-Arm Dumbbell Bench Press",
    description: "Single-arm horizontal press for unilateral chest and trunk control.",
    bodyRegion: "UPPER_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["pectoralis major", "triceps", "anterior deltoid"],
    equipmentRequired: ["dumbbell", "bench"],
    contraindications: ["painful pressing motion"],
    instructions: "Press one dumbbell from the bench while keeping the ribs stacked and the body steady.",
    commonMistakes: "Rotating the torso or arching excessively.",
    defaultSets: 4,
    defaultReps: 8,
    defaultHoldSeconds: null,
    cuesThumbnail: "One arm, steady trunk.",
    videoUrl: "https://www.youtube.com/watch?v=LgCbv-u73vg",
  }),
  seedExercise({
    name: "Shuffle Single-Arm Chest Pass",
    description: "Lateral shuffle into a single-arm chest pass.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["pectorals", "core", "triceps"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["painful shoulder motion"],
    instructions: "Shuffle into position and chest pass the ball with one arm.",
    commonMistakes: "Losing the shuffle rhythm or letting the trunk rotate excessively.",
    defaultSets: 4,
    defaultReps: 6,
    defaultHoldSeconds: null,
    cuesThumbnail: "Shuffle, then fire the pass.",
    videoUrl: "https://www.youtube.com/watch?v=z3s4epg5nVs",
  }),
  seedExercise({
    name: "Dumbbell Shoulder Press",
    description: "Vertical press for shoulder strength.",
    bodyRegion: "UPPER_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["deltoids", "triceps"],
    equipmentRequired: ["dumbbells"],
    contraindications: ["painful overhead motion"],
    instructions: "Press the dumbbells overhead while keeping the ribs down.",
    commonMistakes: "Arching the low back or flaring the elbows.",
    defaultSets: 4,
    defaultReps: 8,
    defaultHoldSeconds: null,
    cuesThumbnail: "Ribs down. Press overhead.",
    videoUrl: "https://www.youtube.com/watch?v=qEwKCR5JCog",
  }),
  seedExercise({
    name: "Step-In Overhead Throw",
    description: "Medicine ball throw with a step-in load.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["glutes", "core", "shoulders"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["painful overhead motion"],
    instructions: "Step in, load the hips, and launch the ball overhead.",
    commonMistakes: "Throwing only with the arms.",
    defaultSets: 4,
    defaultReps: 4,
    defaultHoldSeconds: null,
    cuesThumbnail: "Step in, load, launch.",
    videoUrl: "https://www.youtube.com/watch?v=ryRfwxe5g_o",
  }),
  seedExercise({
    name: "Wrist Stretch Circuit",
    description: "Wrist mobility circuit for pressing and hanging volume.",
    bodyRegion: "UPPER_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "COOLDOWN",
    musclesTargeted: ["wrist flexors", "wrist extensors"],
    equipmentRequired: [],
    contraindications: ["acute wrist fracture"],
    instructions: "Move through wrist flexion and extension stretches with gentle pressure.",
    commonMistakes: "Forcing the range or bouncing the stretch.",
    defaultSets: 1,
    defaultReps: null,
    defaultHoldSeconds: 30,
    cuesThumbnail: "Gentle pressure. Slow breathing.",
    videoUrl: "https://www.youtube.com/watch?v=vDdY8ME8LIE",
  }),
  seedExercise({
    name: "Face Pull",
    description: "Rear-delt and scapular control pull.",
    bodyRegion: "UPPER_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["rear deltoid", "rhomboids", "lower trapezius"],
    equipmentRequired: ["cable or band"],
    contraindications: ["painful shoulder traction"],
    instructions: "Pull the handle toward the face with elbows high and controlled scapular retraction.",
    commonMistakes: "Turning it into a row or shrugging up.",
    defaultSets: 4,
    defaultReps: 8,
    defaultHoldSeconds: null,
    cuesThumbnail: "Elbows high. Pull to face.",
    videoUrl: "https://www.youtube.com/watch?v=0Po47vvj9g4",
  }),
  seedExercise({
    name: "Dumbbell Halo",
    description: "Shoulder mobility drill that circles the weight around the head.",
    bodyRegion: "UPPER_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "WARMUP",
    musclesTargeted: ["shoulders", "upper back"],
    equipmentRequired: ["dumbbell"],
    contraindications: ["painful overhead motion"],
    instructions: "Circle a dumbbell around the head in both directions while keeping the ribs down.",
    commonMistakes: "Arching the back or moving too fast.",
    defaultSets: 4,
    defaultReps: 6,
    defaultHoldSeconds: null,
    cuesThumbnail: "Small controlled circle.",
    videoUrl: "https://www.youtube.com/watch?v=kYo2fBLGpQs",
  }),
  seedExercise({
    name: "Child's Pose",
    description: "Resting stretch for the back and lats.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "COOLDOWN",
    musclesTargeted: ["latissimus dorsi", "spinal extensors"],
    equipmentRequired: [],
    contraindications: ["painful kneeling position"],
    instructions: "Sit back into child’s pose and breathe into the back and sides.",
    commonMistakes: "Forcing the hips too far back.",
    defaultSets: 1,
    defaultReps: null,
    defaultHoldSeconds: 30,
    cuesThumbnail: "Breathe into the back.",
    videoUrl: "https://www.youtube.com/watch?v=_ZX_zTOBgp8",
  }),
  seedExercise({
    name: "Full Range of Motion Push-Up",
    description: "Standard full-range push-up.",
    bodyRegion: "UPPER_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["pectorals", "triceps", "serratus anterior"],
    equipmentRequired: [],
    contraindications: ["painful wrist extension"],
    instructions: "Lower the chest toward the floor and press back up while keeping the body in one line.",
    commonMistakes: "Sagging hips or cutting the range short.",
    defaultSets: 4,
    defaultReps: 8,
    defaultHoldSeconds: null,
    cuesThumbnail: "Chest low. Body rigid.",
    videoUrl: "https://www.youtube.com/watch?v=5yySze8P2DM",
  }),
  seedExercise({
    name: "Bent Over Dumbbell Row",
    description: "Horizontal row with dumbbells.",
    bodyRegion: "UPPER_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["lats", "rhomboids", "mid traps"],
    equipmentRequired: ["dumbbells"],
    contraindications: ["acute low-back pain"],
    instructions: "Hinge forward and row the dumbbells toward the ribs with a stable torso.",
    commonMistakes: "Using momentum or rounding the spine.",
    defaultSets: 4,
    defaultReps: 8,
    defaultHoldSeconds: null,
    cuesThumbnail: "Long spine. Pull to ribs.",
    videoUrl: "https://www.youtube.com/watch?v=fFmwY2dA2ds",
  }),
  seedExercise({
    name: "Dumbbell External Rotation",
    description: "Rotator cuff drill for shoulder stability.",
    bodyRegion: "UPPER_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["infraspinatus", "teres minor"],
    equipmentRequired: ["light dumbbell"],
    contraindications: ["painful shoulder rotation"],
    instructions: "Keep the elbow pinned to the side and rotate the forearm outward against light resistance.",
    commonMistakes: "Using too much weight or letting the elbow drift away.",
    defaultSets: 4,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Elbow pinned. Slow out, slow back.",
    videoUrl: "https://www.youtube.com/watch?v=gOwur9N0cM0",
  }),
  seedExercise({
    name: "Dead Bug",
    description: "Anti-extension core drill.",
    bodyRegion: "CORE",
    difficultyLevel: "BEGINNER",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["rectus abdominis", "transverse abdominis"],
    equipmentRequired: [],
    contraindications: ["sharp low-back pain"],
    instructions: "Lower opposite arm and leg while keeping the low back flat.",
    commonMistakes: "Letting the low back arch.",
    defaultSets: 4,
    defaultReps: 12,
    defaultHoldSeconds: null,
    cuesThumbnail: "Low back stays flat.",
    videoUrl: "https://www.youtube.com/watch?v=bxn9FBrt4-A",
  }),
  seedExercise({
    name: "Kettlebell Lying Pullover Crunch",
    description: "Core and lat integration drill.",
    bodyRegion: "CORE",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["rectus abdominis", "lats", "serratus anterior"],
    equipmentRequired: ["kettlebell"],
    contraindications: ["painful shoulder flexion"],
    instructions: "Lie on your back, crunch up, and control the pullover back overhead.",
    commonMistakes: "Overarching the low back or moving too fast.",
    defaultSets: 4,
    defaultReps: 12,
    defaultHoldSeconds: null,
    cuesThumbnail: "Ribs down. Crunch and pullover.",
    videoUrl: "https://www.youtube.com/watch?v=2EFpuPVkUTQ",
  }),
  seedExercise({
    name: "Resisted Sprint",
    description: "Acceleration sprint with external resistance.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["glutes", "hamstrings", "calves"],
    equipmentRequired: ["hill or resistance"],
    contraindications: ["acute hamstring strain"],
    instructions: "Sprint a short distance against the chosen resistance with clean mechanics.",
    commonMistakes: "Using too much resistance or leaning excessively.",
    defaultSets: 5,
    defaultReps: null,
    defaultHoldSeconds: null,
    cuesThumbnail: "Push hard. Stay clean.",
    videoUrl: "https://www.youtube.com/watch?v=cFsP42jtBvU",
  }),
  seedExercise({
    name: "Assisted Sprint",
    description: "Overspeed sprint drill with gentle assistance.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["glutes", "hamstrings", "calves"],
    equipmentRequired: ["hill or assistance"],
    contraindications: ["acute hamstring strain"],
    instructions: "Run with a slight assist while maintaining posture and quick turnover.",
    commonMistakes: "Overstriding or losing control.",
    defaultSets: 5,
    defaultReps: null,
    defaultHoldSeconds: null,
    cuesThumbnail: "Quick turnover. Stay in control.",
    videoUrl: "https://www.youtube.com/watch?v=f-YFiRQBAOU",
  }),
  seedExercise({
    name: "Normal Sprint",
    description: "Unresisted sprint for speed transfer.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "ADVANCED",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["glutes", "hamstrings", "calves"],
    equipmentRequired: [],
    contraindications: ["acute hamstring strain"],
    instructions: "Sprint the prescribed distance with progressive effort and clean mechanics.",
    commonMistakes: "Reaching for the ground with the foot or losing posture.",
    defaultSets: 5,
    defaultReps: null,
    defaultHoldSeconds: null,
    cuesThumbnail: "Fast, tall, controlled.",
    videoUrl: "https://www.youtube.com/watch?v=9qQ8r0eCFYw",
  }),
  seedExercise({
    name: "Ankle Dribbler",
    description: "Rapid low-amplitude running drill.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "WARMUP",
    musclesTargeted: ["calves", "hip flexors"],
    equipmentRequired: [],
    contraindications: ["acute calf strain"],
    instructions: "Run with very small fast steps, keeping the feet active under the body.",
    commonMistakes: "Lifting the knees too high or making the steps heavy.",
    defaultSets: 2,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Tiny fast steps.",
    videoUrl: "https://www.youtube.com/watch?v=DHv8Q-55TRY",
  }),
  seedExercise({
    name: "A Skip",
    description: "Fundamental running drill for rhythm and knee drive.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "WARMUP",
    musclesTargeted: ["hip flexors", "calves", "glutes"],
    equipmentRequired: [],
    contraindications: ["acute hip flexor strain"],
    instructions: "Drive the knee up and bounce off the ground with a tall torso.",
    commonMistakes: "Leaning back or losing rhythm.",
    defaultSets: 2,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Knee up. Bounce.",
    videoUrl: "https://www.youtube.com/watch?v=GQg9L28bi1g",
  }),
  seedExercise({
    name: "B Skip",
    description: "Advanced running drill with snap-down extension.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "WARMUP",
    musclesTargeted: ["hip flexors", "hamstrings", "calves"],
    equipmentRequired: [],
    contraindications: ["acute hamstring strain"],
    instructions: "Drive the knee, extend the lower leg, then snap it down under the body.",
    commonMistakes: "Overreaching the lower leg or collapsing the trunk.",
    defaultSets: 2,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Drive, extend, snap down.",
    videoUrl: "https://www.youtube.com/watch?v=nlKiHSy6ubA",
  }),
  seedExercise({
    name: "Skips for Distance",
    description: "Skip variation emphasizing horizontal travel.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "WARMUP",
    musclesTargeted: ["hip flexors", "glutes", "calves"],
    equipmentRequired: [],
    contraindications: ["acute calf pain"],
    instructions: "Skip forward with long smooth coverage while staying tall.",
    commonMistakes: "Bounding too hard or overstriding.",
    defaultSets: 2,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Long but smooth.",
    videoUrl: "https://www.youtube.com/watch?v=um2R-OEz0-Q",
  }),
  seedExercise({
    name: "Overhead Rotational Slam",
    description: "Medicine ball power drill combining rotation and overhead force.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["obliques", "lats", "shoulders"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["painful overhead motion"],
    instructions: "Rotate and slam the ball down with force.",
    commonMistakes: "Using the low back or moving too slowly.",
    defaultSets: 3,
    defaultReps: 3,
    defaultHoldSeconds: null,
    cuesThumbnail: "Rotate, reach, slam.",
    videoUrl: "https://www.youtube.com/watch?v=b4PX4H-LYjc",
  }),
  seedExercise({
    name: "Split-Stance Rotational Slam",
    description: "Rotational slam from a split stance.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["obliques", "glutes", "shoulders"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["painful trunk rotation"],
    instructions: "Set in a split stance and rotate through the torso to slam the ball.",
    commonMistakes: "Letting the pelvis spin out.",
    defaultSets: 3,
    defaultReps: 3,
    defaultHoldSeconds: null,
    cuesThumbnail: "Split stance. Slam hard.",
    videoUrl: "https://www.youtube.com/watch?v=Bbu-ojNSWqQ",
  }),
  seedExercise({
    name: "Kneeling Chest Pass",
    description: "Kneeling medicine ball chest pass.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["pectorals", "triceps", "serratus anterior"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["painful shoulder extension"],
    instructions: "Drive the ball straight out from the chest with an explosive release.",
    commonMistakes: "Pushing instead of throwing.",
    defaultSets: 3,
    defaultReps: 5,
    defaultHoldSeconds: null,
    cuesThumbnail: "Quick chest pass.",
    videoUrl: "https://www.youtube.com/watch?v=th_u4qh7WPU",
  }),
  seedExercise({
    name: "Split-Stance Single-Arm Chest Pass",
    description: "Single-arm chest pass from a split stance.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["pectorals", "core", "triceps"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["painful shoulder motion"],
    instructions: "Use one arm to chest pass the medicine ball while keeping the split stance stable.",
    commonMistakes: "Rotating the body excessively.",
    defaultSets: 3,
    defaultReps: 3,
    defaultHoldSeconds: null,
    cuesThumbnail: "One arm, stable base.",
    videoUrl: "https://www.youtube.com/watch?v=NH8_GJYp7XU",
  }),
  seedExercise({
    name: "Standing Chest Pass",
    description: "Standing medicine ball chest pass.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["pectorals", "triceps", "serratus anterior"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["painful shoulder extension"],
    instructions: "Explode the ball straight out from the chest and reset under control.",
    commonMistakes: "Leaning back to generate power.",
    defaultSets: 3,
    defaultReps: 5,
    defaultHoldSeconds: null,
    cuesThumbnail: "Explode from the chest.",
    videoUrl: "https://www.youtube.com/watch?v=pJ8amgzbZMM",
  }),
  seedExercise({
    name: "Scoop Toss",
    description: "Hip-driven medicine ball toss.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "ACTIVATION",
    musclesTargeted: ["glutes", "hamstrings", "shoulders"],
    equipmentRequired: ["medicine ball"],
    contraindications: ["acute low-back pain"],
    instructions: "Load the hips and toss the ball with a smooth explosive finish.",
    commonMistakes: "Squatting too deep or lifting with the arms only.",
    defaultSets: 3,
    defaultReps: 5,
    defaultHoldSeconds: null,
    cuesThumbnail: "Load hips. Scoop. Pop.",
    videoUrl: "https://www.youtube.com/watch?v=GIXjDwOSbd8",
  }),
  seedExercise({
    name: "Deep Push-Up Hold",
    description: "Isometric bottom push-up hold.",
    bodyRegion: "UPPER_BODY",
    difficultyLevel: "INTERMEDIATE",
    exercisePhase: "STRENGTHENING",
    musclesTargeted: ["pectorals", "triceps", "serratus anterior"],
    equipmentRequired: [],
    contraindications: ["painful wrist extension"],
    instructions: "Hold the bottom push-up position with a rigid trunk and active shoulders.",
    commonMistakes: "Sagging hips or shrugging into the shoulders.",
    defaultSets: 5,
    defaultReps: null,
    defaultHoldSeconds: 30,
    cuesThumbnail: "Bottom hold. Body rigid.",
    videoUrl: "https://www.youtube.com/watch?v=Jv2hgtdfcC8",
  }),
  seedExercise({
    name: "90/90 Hip Switches",
    description: "Hip rotation mobility drill.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "MOBILITY",
    musclesTargeted: ["hips", "glutes"],
    equipmentRequired: [],
    contraindications: ["acute hip pain"],
    instructions: "Sit in a 90/90 position and switch the knees side to side with control.",
    commonMistakes: "Leaning excessively with the trunk or rushing the transition.",
    defaultSets: 2,
    defaultReps: 5,
    defaultHoldSeconds: null,
    cuesThumbnail: "Rotate through the hips.",
    videoUrl: "https://www.youtube.com/watch?v=qq_Z7sAmVrA",
  }),
  seedExercise({
    name: "Half-Kneeling Hamstring Stretch",
    description: "Hamstring mobility drill from half-kneeling.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "MOBILITY",
    musclesTargeted: ["hamstrings"],
    equipmentRequired: [],
    contraindications: ["acute hamstring pain"],
    instructions: "From half-kneeling, straighten the front leg and hinge gently.",
    commonMistakes: "Rounding the back or forcing the stretch.",
    defaultSets: 2,
    defaultReps: null,
    defaultHoldSeconds: 30,
    cuesThumbnail: "Tall trunk. Gentle hinge.",
    videoUrl: "https://www.youtube.com/watch?v=EHHUGUMdWDQ",
  }),
  seedExercise({
    name: "Butterfly Stretch",
    description: "Adductor and groin mobility stretch.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "MOBILITY",
    musclesTargeted: ["adductors", "groin"],
    equipmentRequired: [],
    contraindications: ["acute groin strain"],
    instructions: "Bring the soles of the feet together and gently let the knees fall outward.",
    commonMistakes: "Forcing the knees down or rounding the back.",
    defaultSets: 2,
    defaultReps: null,
    defaultHoldSeconds: 30,
    cuesThumbnail: "Sit tall. Knees relax outward.",
    videoUrl: "https://www.youtube.com/watch?v=MdE_Cj6ChLo",
  }),
  seedExercise({
    name: "Open the Gate",
    description: "Dynamic hip mobility drill.",
    bodyRegion: "LOWER_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "WARMUP",
    musclesTargeted: ["hip flexors", "glutes"],
    equipmentRequired: [],
    contraindications: ["acute hip pain"],
    instructions: "Lift one knee, open the hip outward, and step through.",
    commonMistakes: "Twisting through the low back or moving too quickly.",
    defaultSets: 2,
    defaultReps: 5,
    defaultHoldSeconds: null,
    cuesThumbnail: "Knee up, open the hip.",
    videoUrl: "https://www.youtube.com/watch?v=XJem9O8OaTk",
  }),
  seedExercise({
    name: "T-Spine Rotation",
    description: "Thoracic rotation drill.",
    bodyRegion: "UPPER_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "MOBILITY",
    musclesTargeted: ["thoracic spine", "obliques"],
    equipmentRequired: [],
    contraindications: ["acute thoracic pain"],
    instructions: "Rotate the upper back slowly to each side while keeping the pelvis quiet.",
    commonMistakes: "Moving only through the low back.",
    defaultSets: 2,
    defaultReps: 5,
    defaultHoldSeconds: null,
    cuesThumbnail: "Rotate the upper back only.",
    videoUrl: "https://www.youtube.com/watch?v=vFtgYX3YR6A",
  }),
  seedExercise({
    name: "Elephant Walk",
    description: "Dynamic hamstring mobility movement.",
    bodyRegion: "FULL_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "COOLDOWN",
    musclesTargeted: ["hamstrings", "calves", "spine"],
    equipmentRequired: [],
    contraindications: ["acute hamstring pain"],
    instructions: "Hinge forward and alternate gentle knee bends to open the hamstrings.",
    commonMistakes: "Rounding aggressively or bouncing.",
    defaultSets: 1,
    defaultReps: 10,
    defaultHoldSeconds: null,
    cuesThumbnail: "Hinge, alternate knees, breathe.",
    videoUrl: "https://www.youtube.com/watch?v=fnih_6w_JjA",
  }),
  seedExercise({
    name: "Neck Stretch Circuit",
    description: "Gentle neck mobility circuit.",
    bodyRegion: "UPPER_BODY",
    difficultyLevel: "BEGINNER",
    exercisePhase: "COOLDOWN",
    musclesTargeted: ["upper trapezius", "levator scapulae", "cervical extensors"],
    equipmentRequired: [],
    contraindications: ["acute neck injury"],
    instructions: "Move through gentle neck flexion, side-bending, and rotation positions with smooth breathing.",
    commonMistakes: "Forcing painful ranges or shrugging the shoulders.",
    defaultSets: 1,
    defaultReps: null,
    defaultHoldSeconds: 30,
    cuesThumbnail: "Gentle ranges only.",
    videoUrl: "https://www.youtube.com/watch?v=was4RtzpfJs",
  }),
];

const workoutTemplates: TemplateWorkout[] = [
  {
    name: "Lower Body A - Squat Focus",
    description: "Plyometric warm-up, squat strength, unilateral work, and core finish.",
    dayIndex: 0,
    orderIndex: 0,
    estimatedMinutes: 75,
    blocks: [
      {
        name: "Plyometrics",
        type: "WARMUP",
        exercises: [
          { name: "Single-Leg Pogo Hops", sets: makeSets(1, { reps: 15 }), notes: "front, back, side to side" },
          { name: "Double-Leg Pogo Hops", sets: makeSets(1, { reps: 15 }), notes: "front, back, side to side" },
          { name: "Double-Leg Small Pogo Hops", sets: makeSets(1, { reps: 20 }), notes: "10 forward, 10 back" },
          { name: "Double-Leg Pogo for Height", sets: makeSets(1, { reps: 20 }), notes: "10 forward, 10 back" },
          { name: "Split-Stance Slalom Hops", sets: makeSets(1, { reps: 20 }), notes: "each side" },
          { name: "Skips for Height", sets: makeSets(1, { reps: 20 }), notes: "20 yards" },
        ],
      },
      {
        name: "Block A",
        type: "SUPERSET",
        rounds: 4,
        exercises: [
          { name: "Heel Elevated Squat", sets: makeSets(4, { reps: 10 }) },
          { name: "Depth Jump", sets: makeSets(4, { reps: 4 }) },
          { name: "Hamstring Stretch (Supine)", sets: makeSets(1, { durationSeconds: 30 }), notes: "each side" },
        ],
      },
      {
        name: "Block B",
        type: "SUPERSET",
        rounds: 4,
        exercises: [
          { name: "Full Range Split Squat", sets: makeSets(4, { reps: 8 }), notes: "each side" },
          { name: "Skiers", sets: makeSets(4, { reps: 8 }), notes: "each side" },
          { name: "Calf Stretch with Toes Up", sets: makeSets(1, { durationSeconds: 30 }), notes: "each side" },
        ],
      },
      {
        name: "Block C",
        type: "SUPERSET",
        rounds: 4,
        exercises: [
          { name: "Hanging Knee Raise", sets: makeSets(4, { reps: 15 }) },
          { name: "Copenhagen Plank", sets: makeSets(1, { durationSeconds: 30 }), notes: "each side" },
          { name: "Couch Stretch", sets: makeSets(1, { durationSeconds: 30 }), notes: "each side" },
        ],
      },
    ],
  },
  {
    name: "Upper Body A - Pull Focus",
    description: "Med-ball warm-up, pull strength, and trunk/shoulder support work.",
    dayIndex: 1,
    orderIndex: 1,
    estimatedMinutes: 70,
    blocks: [
      {
        name: "Med Ball Warm-Up",
        type: "WARMUP",
        exercises: [
          { name: "Kneeling Overhead Rotational Slam", sets: makeSets(1, { reps: 6 }), notes: "each side" },
          { name: "Kneeling Scoop Toss", sets: makeSets(1, { reps: 6 }), notes: "each side" },
          { name: "Half-Kneeling Overhead Rotational Slam", sets: makeSets(1, { reps: 6 }), notes: "each side" },
          { name: "Half-Kneeling Scoop Toss", sets: makeSets(1, { reps: 6 }), notes: "each side" },
          { name: "Split-Stance Overhead Rotational Slam", sets: makeSets(1, { reps: 6 }), notes: "each side" },
          { name: "Split-Stance Scoop Toss", sets: makeSets(1, { reps: 6 }), notes: "each side" },
        ],
      },
      {
        name: "Block A",
        type: "SUPERSET",
        rounds: 5,
        exercises: [
          { name: "Chin-Up Iso", sets: makeSets(5, { durationSeconds: 30 }) },
          { name: "Step Back Scoop Toss", sets: makeSets(5, { reps: 3 }), notes: "each side" },
          { name: "Shuffle Scoop Toss", sets: makeSets(5, { reps: 4 }), notes: "each side" },
          { name: "Deep Push-Up Hold", sets: makeSets(1, { durationSeconds: 30 }) },
          { name: "Dumbbell External Rotation", sets: makeSets(1, { reps: 8 }), notes: "each side" },
        ],
      },
      {
        name: "Block B",
        type: "SUPERSET",
        rounds: 2,
        exercises: [
          { name: "Half-Kneeling Woodchopper", sets: makeSets(2, { reps: 6 }), notes: "each side" },
          { name: "Dead Hang", sets: makeSets(1, { durationSeconds: 60 }) },
          { name: "Side Plank", sets: makeSets(2, { durationSeconds: 30 }) },
        ],
      },
    ],
  },
  {
    name: "Full Body A - Acceleration Focus",
    description: "Plyo prep, med-ball power, sprint work, and cooldown.",
    dayIndex: 2,
    orderIndex: 2,
    estimatedMinutes: 75,
    blocks: [
      {
        name: "Plyometric Series",
        type: "WARMUP",
        exercises: [
          { name: "Ankle Dribbler", sets: makeSets(2, { reps: 10 }), notes: "2x10 yards" },
          { name: "A Skip", sets: makeSets(2, { reps: 10 }), notes: "2x10 yards" },
          { name: "B Skip", sets: makeSets(2, { reps: 10 }), notes: "2x10 yards" },
          { name: "Broad Jump", sets: makeSets(2, { reps: 5 }), notes: "2x10 yards" },
          { name: "Skips for Distance", sets: makeSets(2, { reps: 10 }), notes: "2x10 yards" },
          { name: "Bounds", sets: makeSets(2, { reps: 10 }), notes: "2x10 yards" },
          { name: "Lateral Broad Jump", sets: makeSets(2, { reps: 10 }), notes: "2x10 yards" },
        ],
      },
      {
        name: "Med Ball Series",
        type: "WARMUP",
        exercises: [
          { name: "Overhead Rotational Slam", sets: makeSets(1, { reps: 3 }), notes: "each side" },
          { name: "Split-Stance Rotational Slam", sets: makeSets(1, { reps: 3 }), notes: "each side" },
          { name: "Step-In Overhead Throw", sets: makeSets(1, { reps: 3 }), notes: "each side" },
          { name: "Scoop Toss", sets: makeSets(1, { reps: 5 }), notes: "each side" },
          { name: "Kneeling Chest Pass", sets: makeSets(1, { reps: 5 }) },
          { name: "Split-Stance Single-Arm Chest Pass", sets: makeSets(1, { reps: 3 }), notes: "each side" },
          { name: "Standing Chest Pass", sets: makeSets(1, { reps: 5 }) },
        ],
      },
      {
        name: "Acceleration Series",
        type: "SUPERSET",
        exercises: [
          { name: "Resisted Sprint", sets: makeSets(5, { reps: 1 }), notes: "15 yards" },
          { name: "Assisted Sprint", sets: makeSets(5, { reps: 1 }), notes: "15 yards" },
          { name: "Normal Sprint", sets: makeSets(5, { reps: 1 }), notes: "15 yards" },
        ],
      },
      {
        name: "Cooldown",
        type: "COOLDOWN",
        exercises: [
          { name: "Elephant Walk", sets: makeSets(1, { reps: 10 }) },
          { name: "Couch Stretch", sets: makeSets(1, { durationSeconds: 60 }), notes: "each side" },
          { name: "Calf Stretch with Toes Up", sets: makeSets(1, { durationSeconds: 60 }), notes: "each side" },
          { name: "T-Spine Rotation", sets: makeSets(1, { reps: 5 }), notes: "each side" },
        ],
      },
    ],
  },
  {
    name: "Lower Body B - Hinge Focus",
    description: "Hinge and unilateral strength with plyometric transfer.",
    dayIndex: 3,
    orderIndex: 3,
    estimatedMinutes: 70,
    blocks: [
      {
        name: "Plyometrics",
        type: "WARMUP",
        exercises: [
          { name: "Broad Jump", sets: makeSets(2, { reps: 5 }), notes: "2x10 yards" },
          { name: "Consecutive Broad Jumps", sets: makeSets(1, { reps: 3 }), notes: "10 yards" },
          { name: "Bounds", sets: makeSets(4, { reps: 5 }), notes: "4x10 yards" },
          { name: "Standing Triple Jump", sets: makeSets(1, { reps: 3 }) },
        ],
      },
      {
        name: "Block A",
        type: "SUPERSET",
        rounds: 4,
        exercises: [
          { name: "Barbell RDL", sets: makeSets(4, { reps: 8 }) },
          { name: "Normal Sprint", sets: makeSets(5, { reps: 1 }), notes: "15 yards" },
          { name: "Couch Stretch", sets: makeSets(1, { durationSeconds: 30 }), notes: "each side" },
        ],
      },
      {
        name: "Block B",
        type: "SUPERSET",
        rounds: 4,
        exercises: [
          { name: "Dumbbell Seated Good Morning", sets: makeSets(4, { reps: 10 }) },
          { name: "Depth Jump", sets: makeSets(4, { reps: 3 }) },
          { name: "Calf Stretch with Toes Up", sets: makeSets(1, { durationSeconds: 30 }), notes: "each side" },
        ],
      },
      {
        name: "Block C",
        type: "SUPERSET",
        rounds: 4,
        exercises: [
          { name: "Hanging Knee Raise", sets: makeSets(4, { reps: 15 }) },
          { name: "Copenhagen Plank", sets: makeSets(1, { durationSeconds: 30 }), notes: "each side" },
          { name: "Dead Bug", sets: makeSets(2, { reps: 12 }), notes: "each side" },
        ],
      },
    ],
  },
  {
    name: "Upper Body B - Push Focus",
    description: "Pressing day with shoulder health and med-ball power support.",
    dayIndex: 4,
    orderIndex: 4,
    estimatedMinutes: 65,
    blocks: [
      {
        name: "Med Ball Series",
        type: "WARMUP",
        exercises: [
          { name: "Kneeling Overhead Rotational Slam", sets: makeSets(1, { reps: 6 }), notes: "each side" },
          { name: "Kneeling Scoop Toss", sets: makeSets(1, { reps: 6 }), notes: "each side" },
          { name: "Half-Kneeling Overhead Rotational Slam", sets: makeSets(1, { reps: 6 }), notes: "each side" },
          { name: "Half-Kneeling Scoop Toss", sets: makeSets(1, { reps: 6 }), notes: "each side" },
          { name: "Split-Stance Overhead Rotational Slam", sets: makeSets(1, { reps: 6 }), notes: "each side" },
          { name: "Split-Stance Scoop Toss", sets: makeSets(1, { reps: 6 }), notes: "each side" },
        ],
      },
      {
        name: "Block A",
        type: "SUPERSET",
        rounds: 4,
        exercises: [
          { name: "Single-Arm Dumbbell Bench Press", sets: makeSets(4, { reps: 8 }), notes: "each side" },
          { name: "Shuffle Single-Arm Chest Pass", sets: makeSets(4, { reps: 6 }), notes: "each side" },
          { name: "Dead Hang", sets: makeSets(1, { durationSeconds: 30 }) },
        ],
      },
      {
        name: "Block B",
        type: "SUPERSET",
        rounds: 4,
        exercises: [
          { name: "Dumbbell Shoulder Press", sets: makeSets(4, { reps: 8 }) },
          { name: "Step-In Overhead Throw", sets: makeSets(4, { reps: 4 }) },
          { name: "Wrist Stretch Circuit", sets: makeSets(1, { durationSeconds: 30 }) },
        ],
      },
      {
        name: "Block C",
        type: "SUPERSET",
        rounds: 4,
        exercises: [
          { name: "Face Pull", sets: makeSets(4, { reps: 8 }) },
          { name: "Dumbbell Halo", sets: makeSets(4, { reps: 6 }), notes: "each side" },
          { name: "Child's Pose", sets: makeSets(1, { durationSeconds: 30 }) },
        ],
      },
    ],
  },
  {
    name: "Full Body B - Max Velo Focus",
    description: "Mobility, elastic plyometrics, and progressive speed work for top-end velocity.",
    dayIndex: 5,
    orderIndex: 5,
    estimatedMinutes: 75,
    blocks: [
      {
        name: "Mobility Series",
        type: "WARMUP",
        exercises: [
          { name: "90/90 Hip Switches", sets: makeSets(1, { reps: 5 }) },
          { name: "Half-Kneeling Hamstring Stretch", sets: makeSets(1, { durationSeconds: 30 }) },
          { name: "T-Spine Rotation", sets: makeSets(1, { reps: 5 }) },
          { name: "Butterfly Stretch", sets: makeSets(1, { durationSeconds: 30 }) },
          { name: "Open the Gate", sets: makeSets(1, { reps: 5 }) },
        ],
      },
      {
        name: "Plyometric Series",
        type: "WARMUP",
        exercises: [
          { name: "Single-Leg Pogo Hops", sets: makeSets(2, { reps: 10 }), notes: "2x10 yards" },
          { name: "Double-Leg Pogo for Height", sets: makeSets(2, { reps: 10 }), notes: "2x10 yards" },
          { name: "A Skip", sets: makeSets(2, { reps: 10 }), notes: "2x10 yards" },
          { name: "B Skip", sets: makeSets(2, { reps: 10 }), notes: "2x10 yards" },
          { name: "Skips for Height", sets: makeSets(2, { reps: 10 }), notes: "2x10 yards" },
          { name: "Broad Jump", sets: makeSets(2, { reps: 5 }), notes: "2x10 yards" },
          { name: "Bounds", sets: makeSets(2, { reps: 10 }), notes: "2x10 yards" },
          { name: "Lateral Broad Jump", sets: makeSets(2, { reps: 5 }), notes: "2x10 yards" },
        ],
      },
      {
        name: "Speed Series",
        type: "SUPERSET",
        exercises: [
          { name: "Normal Sprint", sets: makeSets(3, { reps: 1 }), notes: "30 yards @ 65, 75, 85%" },
          { name: "Normal Sprint", sets: makeSets(3, { reps: 1 }), notes: "40 yards @ 70, 80, 90%" },
          { name: "Normal Sprint", sets: makeSets(2, { reps: 1 }), notes: "60 yards" },
        ],
      },
      {
        name: "Cooldown",
        type: "COOLDOWN",
        exercises: [
          { name: "Elephant Walk", sets: makeSets(1, { reps: 10 }) },
          { name: "90/90 Hip Switches", sets: makeSets(1, { reps: 5 }) },
          { name: "Couch Stretch", sets: makeSets(1, { durationSeconds: 30 }) },
          { name: "Calf Stretch with Toes Up", sets: makeSets(1, { durationSeconds: 30 }) },
          { name: "T-Spine Rotation", sets: makeSets(1, { reps: 5 }) },
        ],
      },
    ],
  },
];

async function ensureExercise(seed: ExerciseSeed): Promise<string> {
  const existing = await prisma.exercise.findFirst({ where: { name: seed.name }, select: { id: true } });
  if (existing) return existing.id;

  const created = await prisma.exercise.create({
    data: {
      ...seed,
      isActive: true,
      videoUrl: seed.videoUrl,
      videoProvider: seed.videoUrl ? "YOUTUBE" : null,
      imageUrl: null,
      createdById: null,
    },
  });

  return created.id;
}

async function clearExistingTemplate(templateName: string) {
  const existing = await prisma.program.findFirst({
    where: { name: templateName, isTemplate: true },
    select: { id: true },
  });

  if (!existing) return;

  await prisma.workout.deleteMany({ where: { programId: existing.id } });
  await prisma.program.delete({ where: { id: existing.id } });
}

async function getTrainerId(): Promise<string> {
  const trainer = await prisma.user.findFirst({
    where: { role: "TRAINER" },
    orderBy: { createdAt: "asc" },
    select: { id: true },
  });

  if (!trainer) {
    throw new Error("No trainer user found. Seed a trainer account first.");
  }

  return trainer.id;
}

async function main() {
  console.log(`Seeding ${exerciseSeeds.length} exercises...`);

  const exerciseIdByName = new Map<string, string>();
  for (const exercise of exerciseSeeds) {
    const id = await ensureExercise(exercise);
    exerciseIdByName.set(exercise.name, id);
  }

  const templateName = "Athletic Performance Template";
  await clearExistingTemplate(templateName);
  const trainerId = await getTrainerId();

  console.log("Creating program template...");

  const program = await prisma.program.create({
    data: {
      name: templateName,
      description: "Imported from the pasted performance plan with lower, upper, and full-body sessions.",
      isTemplate: true,
      durationWeeks: 1,
      daysPerWeek: 6,
      tags: ["power", "speed", "strength", "plyometrics"],
      status: "DRAFT",
      trainerId,
    },
  });

  for (const workout of workoutTemplates) {
    const createdWorkout = await prisma.workout.create({
      data: {
        programId: program.id,
        name: workout.name,
        description: workout.description,
        dayIndex: workout.dayIndex,
        weekIndex: 0,
        orderIndex: workout.orderIndex,
        estimatedMinutes: workout.estimatedMinutes,
      },
    });

    for (const [blockIndex, block] of workout.blocks.entries()) {
      const createdBlock = await prisma.workoutBlockV2.create({
        data: {
          workoutId: createdWorkout.id,
          name: block.name,
          type: block.type,
          orderIndex: blockIndex,
          rounds: block.rounds ?? 1,
          notes: block.notes ?? null,
        },
      });

      for (const [exerciseIndex, exercise] of block.exercises.entries()) {
        const exerciseId = exerciseIdByName.get(exercise.name);
        if (!exerciseId) {
          throw new Error(`Missing exercise id for ${exercise.name}`);
        }

        const createdBlockExercise = await prisma.blockExerciseV2.create({
          data: {
            blockId: createdBlock.id,
            exerciseId,
            orderIndex: exerciseIndex,
            restSeconds: exercise.restSeconds ?? 60,
            notes: exercise.notes ?? null,
          },
        });

        if (exercise.sets.length > 0) {
          await prisma.exerciseSet.createMany({
            data: exercise.sets.map((set, setIndex) => ({
              blockExerciseId: createdBlockExercise.id,
              orderIndex: setIndex,
              setType: "NORMAL",
              targetReps: set.reps ?? null,
              targetDuration: set.durationSeconds ?? null,
            })),
          });
        }
      }
    }
  }

  console.log(`Done. Seeded ${exerciseSeeds.length} exercises and 1 program template.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
