import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const exercises = [
  // ─── LOWER BODY ───────────────────────────────────────────────
  {
    name: "Supine Knee to Chest Stretch",
    description: "Lying on your back, gently pull one knee toward your chest to stretch the lower back and hip.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: ["acute disc herniation"],
    instructions: "Lie on your back. Bend one knee and gently pull it toward your chest with both hands. Hold 20-30 seconds. Switch sides. Repeat 3x each side.",
  },
  {
    name: "Heel Slides",
    description: "Sliding the heel along the floor to improve knee and hip range of motion.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: [],
    instructions: "Lie on your back, legs straight. Slowly slide one heel toward your buttocks, bending the knee. Hold briefly then return. Repeat 10-15 reps each side.",
  },
  {
    name: "Ankle Pumps",
    description: "Pumping the ankle up and down to improve circulation and ankle mobility.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: [],
    instructions: "Sit or lie down. Point your toes away from you, then flex them toward your shin. Repeat in a pumping motion 20-30 times each foot.",
  },
  {
    name: "Short Arc Quads",
    description: "Strengthening the quadriceps through a small range of motion, ideal for post-surgical rehab.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["towel roll"],
    contraindications: ["acute knee surgery within 2 weeks"],
    instructions: "Lie on your back. Place a rolled towel under one knee. Tighten thigh muscle and lift the foot until knee is straight. Hold 5 seconds then lower slowly. 3 sets of 10.",
  },
  {
    name: "Straight Leg Raise",
    description: "Strengthening the hip flexors and quads without knee bend stress.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: ["hip flexor strain"],
    instructions: "Lie on your back. Bend one knee, keep the other straight. Tighten the thigh of the straight leg and raise it to the height of the bent knee. Hold 2 seconds. Lower slowly. 3 sets of 10-15.",
  },
  {
    name: "Clamshells",
    description: "Hip external rotator and gluteus medius strengthening in side-lying position.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: [],
    instructions: "Lie on your side with hips stacked and knees bent at 45°. Keep feet together. Rotate the top knee upward like a clamshell opening, then lower. 3 sets of 15 each side.",
  },
  {
    name: "Clamshells with Resistance Band",
    description: "Hip abductor strengthening with added resistance band for progressive loading.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: ["resistance band"],
    contraindications: [],
    instructions: "Place a resistance band just above the knees. Perform clamshells with the band providing resistance. 3 sets of 12-15 each side.",
  },
  {
    name: "Seated Leg Extension",
    description: "Quad strengthening exercise performed seated in a chair.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["chair"],
    contraindications: ["patellofemoral syndrome"],
    instructions: "Sit upright in a chair. Tighten thigh muscle and slowly extend one leg until straight. Hold 3 seconds. Lower slowly. 3 sets of 10-12 each leg.",
  },
  {
    name: "Standing Hip Abduction",
    description: "Lateral leg raise for hip abductor and gluteus medius strengthening.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["wall (for balance)"],
    contraindications: [],
    instructions: "Stand near a wall for support. Slowly raise one leg out to the side, keeping toes forward. Hold 2 seconds. Lower slowly. 3 sets of 12-15 each leg.",
  },
  {
    name: "Standing Hip Extension",
    description: "Gluteal strengthening through hip extension in standing position.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["wall (for balance)"],
    contraindications: [],
    instructions: "Stand facing a wall. Keeping your back straight and knee straight, slowly move one leg straight back. Hold 2 seconds. Return. 3 sets of 12-15 each leg.",
  },
  {
    name: "Mini Squats",
    description: "Partial squat for knee and hip strengthening with reduced joint stress.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["wall (for balance)"],
    contraindications: ["severe knee arthritis"],
    instructions: "Stand with feet shoulder-width apart. Bend knees to 30-40° (like sitting back slightly). Hold 3 seconds. Return to standing. 3 sets of 10-15.",
  },
  {
    name: "Wall Squats (Wall Slides)",
    description: "Supported squat using a wall for controlled quad and glute strengthening.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["wall"],
    contraindications: ["severe knee arthritis"],
    instructions: "Stand with back against wall, feet 1-2 feet from wall. Slide down until knees are at ~60°. Hold 5-10 seconds. Slide back up. 3 sets of 10.",
  },
  {
    name: "Step-Ups",
    description: "Functional lower extremity strengthening using a step.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: ["step or low stair"],
    contraindications: ["acute knee injury"],
    instructions: "Stand facing a step. Step up with one foot, then bring the other foot up. Step back down leading with the same foot. 3 sets of 10-12 each leg.",
  },
  {
    name: "Lunges",
    description: "Functional lower body strengthening for quads, glutes, and balance.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: [] as string[],
    contraindications: ["patellofemoral syndrome", "knee replacement (recent)"],
    instructions: "Stand with feet together. Step one foot forward and lower your body until both knees are at ~90°. Push back to standing. 3 sets of 10 each leg.",
  },
  {
    name: "Calf Raises",
    description: "Calf muscle strengthening and ankle stability exercise.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["wall (for balance)"],
    contraindications: ["Achilles tendinopathy (acute)"],
    instructions: "Stand with feet hip-width apart near a wall. Rise up onto your toes as high as possible. Hold 2 seconds. Lower slowly. 3 sets of 15-20.",
  },
  {
    name: "Single Leg Calf Raises",
    description: "Advanced calf strengthening on one leg for improved ankle stability.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "ADVANCED" as const,
    equipmentRequired: ["wall (for balance)"],
    contraindications: ["Achilles tendinopathy (acute)"],
    instructions: "Stand on one foot near a wall. Rise up onto your toes. Hold 2 seconds. Lower slowly. 3 sets of 12-15 each foot.",
  },
  {
    name: "Hip Flexor Stretch (Kneeling Lunge)",
    description: "Kneeling stretch targeting the hip flexors and psoas.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["mat"],
    contraindications: ["acute knee pain"],
    instructions: "Kneel on one knee with the other foot in front. Shift weight forward until you feel a stretch in the front of the hip on the kneeling side. Hold 30 seconds. 3 reps each side.",
  },
  {
    name: "Hamstring Stretch (Supine)",
    description: "Lying hamstring stretch using a towel or strap.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["towel or strap"],
    contraindications: ["acute hamstring tear"],
    instructions: "Lie on your back. Loop a towel around one foot. Straighten the knee while pulling the leg toward you. Hold 30 seconds. 3 reps each side.",
  },
  {
    name: "Glute Bridges",
    description: "Glute and hamstring strengthening with core stability.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: [],
    instructions: "Lie on your back, knees bent, feet flat. Squeeze glutes and lift hips off the floor until body forms a straight line from knees to shoulders. Hold 3 seconds. Lower slowly. 3 sets of 12-15.",
  },
  {
    name: "Single Leg Glute Bridge",
    description: "Unilateral glute bridge for advanced hip and posterior chain strengthening.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: [] as string[],
    contraindications: [],
    instructions: "Lie on your back. Bend both knees. Extend one leg straight. Squeeze the glute of the planted foot and lift hips. Hold 3 seconds. Lower. 3 sets of 10 each side.",
  },
  {
    name: "Terminal Knee Extension with Band",
    description: "Targeted VMO and quad activation at terminal range of knee extension.",
    bodyRegion: "LOWER_BODY" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: ["resistance band"],
    contraindications: [],
    instructions: "Secure band behind knee. Stand with knee slightly bent. Straighten knee against band resistance. Hold 2 seconds. 3 sets of 15 each leg.",
  },

  // ─── UPPER BODY ───────────────────────────────────────────────
  {
    name: "Pendulum Exercise",
    description: "Gentle shoulder mobility exercise using gravity and momentum.",
    bodyRegion: "UPPER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: ["acute rotator cuff tear"],
    instructions: "Lean forward, supporting yourself on a table with the uninvolved arm. Let the involved arm hang freely. Gently swing the arm in small circles (10 clockwise, 10 counter-clockwise) and side to side. Relax the shoulder completely.",
  },
  {
    name: "Shoulder Pendulum with Weight",
    description: "Pendulum exercise with light weight for progressive shoulder mobility.",
    bodyRegion: "UPPER_BODY" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: ["light dumbbell (1-2 lb)"],
    contraindications: ["acute rotator cuff tear"],
    instructions: "Hold a 1-2 lb weight. Lean forward supporting on a table. Let the weighted arm swing gently in circles. Perform 15 circles each direction.",
  },
  {
    name: "Shoulder Flexion (Table Slide)",
    description: "Passive-assisted shoulder flexion using a table surface.",
    bodyRegion: "UPPER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["table"],
    contraindications: [],
    instructions: "Sit at a table. Place forearm on table surface. Slide arm forward across the table to raise the shoulder into flexion as far as comfortable. Hold briefly. Return. 3 sets of 10.",
  },
  {
    name: "Shoulder External Rotation with Band",
    description: "Rotator cuff strengthening targeting the infraspinatus and teres minor.",
    bodyRegion: "UPPER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["resistance band"],
    contraindications: [],
    instructions: "Attach band at elbow height. Stand sideways to the anchor. Bend elbow to 90° and rotate arm outward (away from body) against band resistance. Hold 2 seconds. 3 sets of 15.",
  },
  {
    name: "Shoulder Internal Rotation with Band",
    description: "Rotator cuff strengthening targeting the subscapularis.",
    bodyRegion: "UPPER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["resistance band"],
    contraindications: [],
    instructions: "Attach band at elbow height. Stand sideways to the anchor. Bend elbow 90°. Rotate arm inward (across body) against band resistance. Hold 2 seconds. 3 sets of 15.",
  },
  {
    name: "Scapular Retraction",
    description: "Postural exercise strengthening the middle trapezius and rhomboids.",
    bodyRegion: "UPPER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: [],
    instructions: "Sit or stand upright. Squeeze shoulder blades together as if pinching a pencil between them. Hold 5 seconds. Release. 3 sets of 15. Keep shoulders down, not elevated.",
  },
  {
    name: "Wall Push-Up",
    description: "Modified push-up against a wall for upper extremity strengthening with reduced load.",
    bodyRegion: "UPPER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["wall"],
    contraindications: ["acute shoulder surgery"],
    instructions: "Stand arm's length from wall, hands at shoulder height/width. Bend elbows to bring chest toward wall. Push back. Keep body straight. 3 sets of 10-15.",
  },
  {
    name: "Wrist Flexion/Extension Stretch",
    description: "Stretching the wrist flexors and extensors to improve wrist mobility.",
    bodyRegion: "UPPER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: ["carpal tunnel (severe)"],
    instructions: "Extend arm with palm up. Use other hand to gently bend wrist down. Hold 20-30 seconds. Then turn palm down and gently bend wrist up. Hold 20-30 seconds. 3 reps each direction.",
  },
  {
    name: "Theraband Rows",
    description: "Upper back and bicep strengthening using a resistance band row motion.",
    bodyRegion: "UPPER_BODY" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: ["resistance band"],
    contraindications: [],
    instructions: "Anchor band at waist height. Hold band with both hands, arms extended. Pull elbows back squeezing shoulder blades together. Hold 2 seconds. Slowly extend. 3 sets of 12-15.",
  },
  {
    name: "Shoulder Elevation Shrugs",
    description: "Upper trapezius and cervical stability exercise.",
    bodyRegion: "UPPER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: ["cervical disc herniation"],
    instructions: "Sit or stand. Slowly elevate shoulders up toward ears. Hold 3 seconds. Lower slowly. 3 sets of 10-12.",
  },
  {
    name: "Bicep Curls with Band",
    description: "Elbow flexor strengthening using a resistance band.",
    bodyRegion: "UPPER_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["resistance band"],
    contraindications: [],
    instructions: "Stand on the band, hold ends with both hands, palms up. Curl hands toward shoulders. Hold 2 seconds. Lower slowly. 3 sets of 12.",
  },
  {
    name: "Tricep Extension with Band",
    description: "Elbow extensor strengthening using overhead resistance band.",
    bodyRegion: "UPPER_BODY" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: ["resistance band"],
    contraindications: [],
    instructions: "Anchor band overhead. Hold with one or both hands behind head, elbows bent. Straighten elbows to extend overhead. Hold 2 seconds. 3 sets of 12.",
  },

  // ─── CORE ─────────────────────────────────────────────────────
  {
    name: "Diaphragmatic Breathing",
    description: "Core activation and relaxation through proper breathing mechanics.",
    bodyRegion: "CORE" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: [],
    instructions: "Lie on your back, knees bent. Place one hand on chest, one on belly. Breathe in through nose expanding belly (not chest). Breathe out slowly. Practice 5-10 minutes.",
  },
  {
    name: "Pelvic Tilts",
    description: "Lumbar spine mobility and core activation exercise.",
    bodyRegion: "CORE" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: [],
    instructions: "Lie on your back, knees bent. Gently flatten lower back into the floor by tightening abdominals. Hold 5 seconds. Release. 3 sets of 10-15.",
  },
  {
    name: "Dead Bug",
    description: "Core stability exercise coordinating opposite arm and leg movement.",
    bodyRegion: "CORE" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: [] as string[],
    contraindications: ["acute low back pain"],
    instructions: "Lie on back, arms straight up toward ceiling, hips and knees at 90°. Slowly lower opposite arm and leg toward floor while keeping lower back pressed down. Return. Alternate sides. 3 sets of 8-10 each side.",
  },
  {
    name: "Bird Dog",
    description: "Quadruped exercise for core stability and spinal control.",
    bodyRegion: "CORE" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: [] as string[],
    contraindications: ["acute low back pain"],
    instructions: "Start on hands and knees. Simultaneously extend one arm forward and the opposite leg back, keeping back flat. Hold 3-5 seconds. Return. Alternate sides. 3 sets of 10 each side.",
  },
  {
    name: "Abdominal Hollowing",
    description: "Deep core (transversus abdominis) activation exercise.",
    bodyRegion: "CORE" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: [],
    instructions: "Lie on back, knees bent. Breathe in normally. Breathe out and draw belly button gently toward spine without moving the pelvis. Hold 10 seconds. Release. 3 sets of 10.",
  },
  {
    name: "Curl-Ups (Modified Crunch)",
    description: "Partial curl-up for rectus abdominis strengthening with reduced spinal load.",
    bodyRegion: "CORE" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: ["cervical spine issues", "recent abdominal surgery"],
    instructions: "Lie on back, one knee bent. Place hands under lower back for support. Nod chin and lift shoulders slightly off floor. Hold 7-8 seconds. Lower slowly. 3 sets of 8-10.",
  },
  {
    name: "Side Plank (Modified)",
    description: "Lateral core strengthening in a modified side plank from the knees.",
    bodyRegion: "CORE" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["mat"],
    contraindications: ["shoulder injury"],
    instructions: "Lie on side, knees bent. Support on forearm and bent knees. Lift hips to create straight line from knees to head. Hold 15-20 seconds. 3 reps each side.",
  },
  {
    name: "Side Plank (Full)",
    description: "Full lateral core strengthening in a side plank position.",
    bodyRegion: "CORE" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: ["mat"],
    contraindications: ["shoulder injury"],
    instructions: "Lie on side, legs straight. Support on forearm and side of foot. Lift hips to create straight line from feet to head. Hold 20-30 seconds. 3 reps each side.",
  },
  {
    name: "Prone Hip Extension (Superman)",
    description: "Posterior chain and lower back strengthening in prone position.",
    bodyRegion: "CORE" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["mat"],
    contraindications: ["acute lumbar disc herniation"],
    instructions: "Lie face down, legs straight, arms by sides. Squeeze glutes and lift one leg slightly off the floor. Hold 3 seconds. Lower. Alternate legs. 3 sets of 10 each side.",
  },
  {
    name: "Plank (Forearm)",
    description: "Isometric core stability exercise in forearm plank position.",
    bodyRegion: "CORE" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: ["mat"],
    contraindications: ["shoulder injury", "wrist pain"],
    instructions: "Support on forearms and toes. Keep body in straight line from head to heels. Engage core and glutes. Hold 20-30 seconds, building to 60 seconds. 3 sets.",
  },

  // ─── BALANCE ──────────────────────────────────────────────────
  {
    name: "Single Leg Stance",
    description: "Basic balance training on one leg to improve proprioception and stability.",
    bodyRegion: "BALANCE" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["wall (for safety)"],
    contraindications: [],
    instructions: "Stand near a wall for safety. Lift one foot slightly off the ground. Balance for 10-20 seconds without touching the wall. 3 reps each leg. Progress to 30 seconds.",
  },
  {
    name: "Tandem Stance",
    description: "Balance exercise standing heel-to-toe to challenge stability.",
    bodyRegion: "BALANCE" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: [],
    instructions: "Place one foot directly in front of the other (heel to toe). Hold balance 10-20 seconds. 3 reps each foot in front. Use wall nearby for safety.",
  },
  {
    name: "Single Leg Stance with Eyes Closed",
    description: "Advanced proprioception exercise removing visual feedback.",
    bodyRegion: "BALANCE" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: ["wall (for safety)"],
    contraindications: ["severe balance disorders", "vertigo"],
    instructions: "Stand near wall. Balance on one leg. Slowly close eyes. Hold 10-15 seconds. 3 reps each leg. Only progress to eyes closed when 30 seconds open-eye stance is mastered.",
  },
  {
    name: "Heel-to-Toe Walking",
    description: "Functional balance and coordination training in tandem gait pattern.",
    bodyRegion: "BALANCE" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: [],
    instructions: "Walk in a straight line placing heel directly in front of opposite toes with each step. Arms out for balance. Walk 10-15 steps forward and back. 3 sets.",
  },
  {
    name: "Balance Board Standing",
    description: "Multi-directional proprioceptive training using a balance board.",
    bodyRegion: "BALANCE" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: ["balance board or wobble board"],
    contraindications: ["ankle instability (severe)"],
    instructions: "Stand on balance board with feet shoulder-width apart. Keep board level as long as possible. Start with 30 seconds, progress to 2 minutes. 3 sets.",
  },
  {
    name: "Sit-to-Stand",
    description: "Functional transfer exercise for lower extremity strength and balance.",
    bodyRegion: "BALANCE" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["chair"],
    contraindications: [],
    instructions: "Sit at the edge of a sturdy chair. Place feet hip-width apart. Lean slightly forward and push through heels to stand. Slowly lower back to seated. 3 sets of 10.",
  },
  {
    name: "Step-Over-Step Stair Climbing",
    description: "Functional stair negotiation exercise for balance and lower limb strength.",
    bodyRegion: "BALANCE" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: ["staircase with railing"],
    contraindications: ["acute knee or hip injury"],
    instructions: "Using a handrail for safety, ascend stairs step-over-step (alternating feet). Descend slowly. 3 sets of one flight up and down.",
  },

  // ─── FLEXIBILITY ──────────────────────────────────────────────
  {
    name: "Cat-Cow Stretch",
    description: "Spinal mobility exercise for the thoracic and lumbar spine.",
    bodyRegion: "FLEXIBILITY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["mat"],
    contraindications: ["acute vertebral fracture"],
    instructions: "Start on hands and knees. Arch back toward ceiling (cat), hold 3 seconds. Then sag belly toward floor lifting head and tailbone (cow), hold 3 seconds. 10-15 cycles.",
  },
  {
    name: "Thoracic Rotation Stretch",
    description: "Improving thoracic spine rotation for posture and upper back mobility.",
    bodyRegion: "FLEXIBILITY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["chair"],
    contraindications: [],
    instructions: "Sit sideways in a chair. Hold the back of the chair and rotate your trunk toward it. Hold 20-30 seconds. Rotate to the opposite side. 3 reps each direction.",
  },
  {
    name: "Piriformis Stretch (Figure 4)",
    description: "Deep hip external rotator and piriformis muscle stretch.",
    bodyRegion: "FLEXIBILITY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: ["hip replacement (anterior approach, recent)"],
    instructions: "Lie on back, knees bent. Cross one ankle over the opposite knee. Pull both legs toward chest until stretch is felt in the buttock. Hold 30 seconds. 3 reps each side.",
  },
  {
    name: "Doorway Pectoral Stretch",
    description: "Chest and anterior shoulder stretch using a doorframe.",
    bodyRegion: "FLEXIBILITY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["doorway"],
    contraindications: ["shoulder instability"],
    instructions: "Stand in a doorway with elbows at 90° and forearms on the doorframe. Lean forward gently until you feel a stretch across the chest. Hold 30 seconds. 3 reps.",
  },
  {
    name: "Seated Piriformis Stretch",
    description: "Chair-based piriformis and hip rotator stretch for office or seated settings.",
    bodyRegion: "FLEXIBILITY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["chair"],
    contraindications: ["hip replacement (anterior approach, recent)"],
    instructions: "Sit upright. Cross one ankle over the opposite knee. Gently press down on the bent knee and lean forward slightly. Hold 30 seconds. 3 reps each side.",
  },
  {
    name: "Standing Quad Stretch",
    description: "Standing stretch for the quadriceps and hip flexors.",
    bodyRegion: "FLEXIBILITY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["wall (for balance)"],
    contraindications: ["knee instability"],
    instructions: "Stand on one leg (use wall for support). Bend the other knee and hold the ankle. Gently pull heel toward buttocks. Hold 30 seconds. 3 reps each leg.",
  },
  {
    name: "Neck Side Flexion Stretch",
    description: "Lateral neck stretch for the upper trapezius and cervical lateral flexors.",
    bodyRegion: "FLEXIBILITY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: ["cervical radiculopathy"],
    instructions: "Sit or stand with shoulders relaxed. Gently tilt ear toward shoulder. Place same-side hand on head for gentle overpressure. Hold 20-30 seconds. 3 reps each side.",
  },

  // ─── FULL BODY ────────────────────────────────────────────────
  {
    name: "Aquatic Walking (Water Walking)",
    description: "Low-impact full body exercise in chest-deep water for joint pain.",
    bodyRegion: "FULL_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["pool"],
    contraindications: ["open wounds", "active infection"],
    instructions: "Walk forward and backward in chest-deep water for 10-20 minutes. High knee walk, side-steps, and backward walking variations. Progress duration weekly.",
  },
  {
    name: "Chair-Based Full Body Workout",
    description: "Seated full body exercise routine suitable for limited mobility individuals.",
    bodyRegion: "FULL_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: ["chair"],
    contraindications: [],
    instructions: "Perform each for 10 reps: seated marching, seated arm circles, seated knee extensions, seated side bends, seated shoulder press. 2-3 rounds.",
  },
  {
    name: "Standing March",
    description: "Functional full body movement for gait, coordination, and core stability.",
    bodyRegion: "FULL_BODY" as const,
    difficultyLevel: "BEGINNER" as const,
    equipmentRequired: [] as string[],
    contraindications: [],
    instructions: "Stand tall. March in place lifting knees to hip height while swinging opposite arm. Keep posture upright. 2-3 minutes continuous or 3 sets of 30 seconds.",
  },
  {
    name: "Resistance Band Full Body Circuit",
    description: "A circuit of resistance band exercises targeting all major muscle groups.",
    bodyRegion: "FULL_BODY" as const,
    difficultyLevel: "INTERMEDIATE" as const,
    equipmentRequired: ["resistance band"],
    contraindications: [],
    instructions: "Perform 12 reps each with minimal rest: band squats, band rows, band shoulder press, band deadlifts. 3 full circuits.",
  },
];

async function main() {
  console.log("Seeding exercise library...");

  let created = 0;
  let skipped = 0;

  for (const exercise of exercises) {
    const existing = await prisma.exercise.findFirst({
      where: { name: exercise.name },
    });

    if (existing) {
      skipped++;
      continue;
    }

    await prisma.exercise.create({
      data: {
        ...exercise,
        isActive: true,
      },
    });
    created++;
  }

  console.log(`✓ Done: ${created} exercises created, ${skipped} already existed.`);
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
