"use server";

import { requireSuperAdmin } from "@/lib/current-user";
import * as programService from "@/lib/services/program.service";
import { createProgramSchema, updateProgramSchema } from "@/lib/validators/program";
import type { CreateProgramInput, UpdateProgramInput } from "@/lib/validators/program";
import { revalidatePath } from "next/cache";
import { generateProgram } from "@/lib/services/ai.service";
import { prisma } from "@/lib/prisma";
import type { WeekPlan } from "@/lib/ai/types/program-generation";

export async function createGlobalProgramAction(input: CreateProgramInput) {
  await requireSuperAdmin();

  const parsed = createProgramSchema.safeParse(input);
  if (!parsed.success) {
    return { success: false as const, error: parsed.error.issues[0].message };
  }

  try {
    const program = await programService.createGlobalProgram(parsed.data);
    revalidatePath("/admin/global-programs");
    return { success: true as const, data: { id: program.id } };
  } catch (error) {
    console.error("Failed to create global program:", error);
    return { success: false as const, error: "Failed to create global program" };
  }
}

export async function updateGlobalProgramAction(
  programId: string,
  input: UpdateProgramInput
) {
  await requireSuperAdmin();

  const parsed = updateProgramSchema.safeParse(input);
  if (!parsed.success) {
    return { success: false as const, error: parsed.error.issues[0].message };
  }

  try {
    const updated = await programService.updateGlobalProgram(programId, parsed.data);
    revalidatePath("/admin/global-programs");
    revalidatePath(`/admin/global-programs/${programId}/edit`);
    return { success: true as const, data: { id: updated.id } };
  } catch (error) {
    console.error("Failed to update global program:", error);
    return { success: false as const, error: "Failed to update global program" };
  }
}

export async function pushGlobalProgramUpdateAction(programId: string) {
  await requireSuperAdmin();

  try {
    await programService.pushGlobalProgramUpdate(programId);
    revalidatePath("/admin/global-programs");
    return { success: true as const };
  } catch (error) {
    console.error("Failed to push global program update:", error);
    return { success: false as const, error: "Failed to push update" };
  }
}

export async function deleteGlobalProgramAction(programId: string) {
  await requireSuperAdmin();

  try {
    await programService.deleteGlobalProgram(programId);
    revalidatePath("/admin/global-programs");
    return { success: true as const };
  } catch (error) {
    console.error("Failed to delete global program:", error);
    return { success: false as const, error: "Failed to delete global program" };
  }
}

export async function generateGlobalProgramAction(params: {
  focusAreas?: string[];
  durationMinutes?: number;
  daysPerWeek?: number;
  durationWeeks?: number;
  circuits?: unknown[];
  preferredWeekdays?: string[];
  difficultyLevel?: string;
  weekPlan?: WeekPlan[];
  [key: string]: unknown;
}) {
  await requireSuperAdmin();

  try {
    const aiPlan = await generateProgram(params as Parameters<typeof generateProgram>[0]);

    // Use the parallel insert pattern — programme shell, then workouts, blocks, exercises, sets
    const program = await prisma.program.create({
      data: {
        name: aiPlan.name,
        description: aiPlan.description || "Generated by AI",
        isGlobal: true,
        isTemplate: false,
        trainerId: null,
        status: "DRAFT",
        aiGenerationParams: params as import("@prisma/client").Prisma.InputJsonValue,
      },
      select: { id: true },
    });

    const createdWorkouts = await Promise.all(
      aiPlan.workouts.map((w) =>
        prisma.workout.create({
          data: {
            programId: program.id,
            name: w.name,
            dayIndex: w.dayIndex,
            weekIndex: w.weekIndex ?? 0,
            orderIndex: (w.weekIndex ?? 0) * 7 + w.dayIndex,
          },
          select: { id: true, dayIndex: true },
        })
      )
    );

    const blockInputs = aiPlan.workouts.flatMap((w, wi) =>
      w.blocks.map((b) => ({ workoutId: createdWorkouts[wi].id, block: b }))
    );
    const createdBlocks = await Promise.all(
      blockInputs.map(({ workoutId, block: b }) =>
        prisma.workoutBlockV2.create({
          data: {
            workoutId,
            type: b.type || "NORMAL",
            name: b.name || b.type || "NORMAL",
            orderIndex: b.orderIndex,
            rounds: b.rounds ?? 1,
            restBetweenRounds: b.restBetweenRounds ?? null,
          },
          select: { id: true },
        })
      )
    );

    const exerciseInputs = blockInputs.flatMap(({ block: b }, bi) =>
      b.exercises.map((e) => ({ blockId: createdBlocks[bi].id, exercise: e }))
    );
    const createdExercises = await Promise.all(
      exerciseInputs.map(({ blockId, exercise: e }) =>
        prisma.blockExerciseV2.create({
          data: {
            blockId,
            exerciseId: e.exerciseId,
            orderIndex: e.orderIndex,
            notes: e.notes ?? null,
            restSeconds: e.restSeconds ?? null,
          },
          select: { id: true },
        })
      )
    );

    const allSets = exerciseInputs.flatMap(({ exercise: e }, ei) => {
      const repStr = e.reps?.toString() ?? "10";
      const isDuration = repStr.endsWith("s");
      const targetReps = isDuration ? null : parseInt(repStr, 10) || null;
      const targetDuration = isDuration ? parseInt(repStr.replace("s", ""), 10) || null : null;
      return Array.from({ length: Math.max(1, e.sets || 1) }).map((_, i) => ({
        blockExerciseId: createdExercises[ei].id,
        orderIndex: i,
        setType: "NORMAL" as const,
        ...(targetReps !== null ? { targetReps } : {}),
        ...(targetDuration !== null ? { targetDuration } : {}),
      }));
    });
    if (allSets.length > 0) {
      await prisma.exerciseSet.createMany({ data: allSets });
    }

    revalidatePath("/admin/global-programs");
    return { success: true as const, data: program.id };
  } catch (error) {
    console.error("Failed to generate global program:", error);
    return { success: false as const, error: "Failed to generate global program" };
  }
}
